version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '9:00'
      timezone: 'Asia/Bangkok'
    open-pull-requests-limit: 10
    reviewers: 
      - 'queq1890'
