name: check

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install
      - name: Run typecheck
        run: yarn typecheck
      - name: Run eslint
        run: yarn lint
      - name: Run test
        run: yarn test
