name: check

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install
      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: './**/*.{ts,tsx}'
      - name: Run typecheck
        run: yarn typecheck
      - name: Run eslint
        run: yarn lint
      - name: Run test
        run: yarn test
